name: utility_flutter
description: A utility package for common HTTP operations with built-in error handling.
version: 0.0.5-dev.1
homepage: https://github.com/navneetprajapati26/utility_flutter

environment:
  sdk: '>=3.1.0-40.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
# ... [rest remains unchanged]
